# Generated by Django 4.2.4 on 2023-08-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_studio'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecollection',
            name='games_list',
            field=models.ManyToManyField(blank=True, related_name='game_collection_list', to='games.game'),
        ),
    ]
